### ISSUE TITLE
Error with initial npm install

### ISSUE THREAD

**Issue by waylonis** [Kira272921/tailwindcsscli#1]
When trying to install the initial shell, I received some errors:

57 error code EACCES
58 error syscall symlink
59 error path ../lib/node_modules/tailwindcli/bin/index.js
60 error dest /usr/local/bin/tcli
61 error errno -13
62 error Error: EACCES: permission denied, symlink '../lib/node_modules/tailwindcli/bin/index.js' -> '/usr/local/bin/tcli'
62 error  [Error: EACCES: permission denied, symlink '../lib/node_modules/tailwindcli/bin/index.js' -> '/usr/local/bin/tcli'] {
62 error   errno: -13,
62 error   code: 'EACCES',
62 error   syscall: 'symlink',
62 error   path: '../lib/node_modules/tailwindcli/bin/index.js',
62 error   dest: '/usr/local/bin/tcli'
62 error }
63 error The operation was rejected by your operating system.
63 error It is likely you do not have the permissions to access this file as the current user

It's a permission issue with /usr/local/bin but I think many OS configurations don't have that directory user writable. It looks like there are some directions with npm to workaround: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by 0xMukesh** [comment]
Hey did you try this [solution](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) provided by npm?

**Comment by waylonis** [comment]
I did and it worked perfectly! You might include a link to that in your writeup after that first step, just to make sure that people don't get stuck.

**Comment by 0xMukesh** [comment]
@waylonis, Thanks for letting me know about the issue 😄. I'll edit the article and add the link
